/**
 * This java source file was generated by the Gradle 'init' task.
 */
package ses.seq.logback.appender;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
