/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ses.seq.logback.appender;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.classic.spi.LoggingEvent;
import org.junit.Test;

import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class SeqLogEventLayoutTest {
    @Test public void testDoLayoutMethod() {
        long currentTimeMillis = System.currentTimeMillis();
        Format dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        Date date = new Date(currentTimeMillis);
        String dateStr = dateFormat.format(date);

        SeqLogEventLayout classUnderTest = new SeqLogEventLayout();
        LoggingEvent loggingEvent = new LoggingEvent();
        loggingEvent.setMessage("test");
        loggingEvent.setLevel(Level.INFO);
        loggingEvent.setThreadName("test-thread");
        loggingEvent.setTimeStamp(currentTimeMillis);

        String layout = classUnderTest.doLayout(loggingEvent);
        assertEquals("doLayout should return formatted string", "{\"@t\":\"" + dateStr + "\",\"@m\":\"test\",\"@l\":\"INFO\",\"ThreadName\":\"test-thread\"}\n", layout);
    }
}
